### ISSUE TITLE
internal server Error upon login saml, latest version

### ISSUE THREAD

**Issue by ChessSpider** [nextcloud/user_saml#296]
### Steps to reproduce
1. Update to latest version
2. Login
3. Error

### Expected behaviour
No error

### Actual behaviour
```
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: [asdadasdsad]
    Request ID: IkGtMmDru1y054VZvjKf
    Type: Error
    Code: 0
    Message: Call to a member function item() on bool
    File: /var/www/html/custom_apps/user_saml/3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php
    Line: 501


Trace

#0 /var/www/html/custom_apps/user_saml/3rdparty/vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php(591): RobRichards\XMLSecLibs\XMLSecurityDSig->processRefNode(Object(DOMElement))
#1 /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Utils.php(1412): RobRichards\XMLSecLibs\XMLSecurityDSig->validateReference()
#2 /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Response.php(410): OneLogin\Saml2\Utils::validateSign(Object(DOMDocument), '-----BEGIN CERT...', '', 'sha1', '/samlp:Response...', NULL)
#3 /var/www/html/custom_apps/user_saml/3rdparty/vendor/onelogin/php-saml/src/Saml2/Auth.php(226): OneLogin\Saml2\Response->isValid('ONELOGIN_87834d...')
#4 /var/www/html/custom_apps/user_saml/lib/Controller/SAMLController.php(251): OneLogin\Saml2\Auth->processResponse('ONELOGIN_87834d...')
#5 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\User_SAML\Controller\SAMLController->assertionConsumerService()
#6 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\User_SAML\Controller\SAMLController), 'assertionConsum...')
#7 /var/www/html/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\User_SAML\Controller\SAMLController), 'assertionConsum...')
#8 /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\User_SAML\\C...', 'assertionConsum...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#9 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#10 /var/www/html/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#11 /var/www/html/lib/base.php(987): OC\Route\Router->match('/apps/user_saml...')
#12 /var/www/html/index.php(42): OC::handleRequest()
#13 {main}

```

### Server configuration
```
        "user_saml": {
            "enabled": "yes",
            "general-require_provisioned_account": "0",
            "general-uid_mapping": "urn:oid:0.9.2342.19200300.100.1.1",
            "idp-entityId": "https:\/\/\/simplesaml\/saml2\/idp\/metadata.php",
            "idp-singleSignOnService.url": "https:\/\\/simplesaml\/saml2\/idp\/SSOService.php",
            "idp-x509cert": "-----BEGIN CERTIFICATE-----MIIE-----END CERTIFICATE-----",
            "installed_version": "2.1.0",
            "saml-attribute-mapping-displayName_mapping": "urn:oid:2.16.840.1.113730.3.1.241",
            "saml-attribute-mapping-email_mapping": "urn:oid:0.9.2342.19200300.100.1.3",
            "security-authnRequestsSigned": "0",
            "security-logoutRequestSigned": "0",
            "security-logoutResponseSigned": "0",
            "security-signMetadata": "0",
            "security-wantAssertionsEncrypted": "0",
            "security-wantAssertionsSigned": "1",
            "security-wantMessagesSigned": "1",
            "security-wantNameId": "1",
            "security-wantXMLValidation": "1",
            "type": "saml",
            "types": "authentication"
        },
```
**Operating system**:
linux
**Web server:**
docker/nginx
**Database:**
iunno
**PHP version:**
```
www-data@f7f9aa59e439:~/html$ php --version
PHP 7.3.1 (cli) (built: Jan 11 2019 00:38:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies
```
**Nextcloud version:** (see Nextcloud admin page)

15.0.2

**Where did you install Nextcloud from:**
docker

**List of activated apps:**
```
www-data@f7f9aa59e439:~/html$ ./occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - user_saml: 2.1.0
  - workflowengine: 1.5.0
```

**Comment by ChessSpider** [comment]
Please let me know if any more info is required. I had to disable user_saml for now, but that's a big problem for my organization. So any assistance is very much appreciated

**Comment by ChessSpider** [comment]
example saml response

```
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_b22715d12d722a8c2a80aaaaaaaaaaaa" Version="2.0" IssueInstant="2019-01-16T10:03:29Z" Destination="https://cloud.domain.com/apps/user_saml/saml/acs" InResponseTo="ONELOGIN_e79aaaaaaaaaaaaaaaaaaaaaa">
    <saml:Issuer>https://sso.domain.com/simplesaml/saml2/idp/metadata.php</saml:Issuer>
    <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
    <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
  <ds:Reference URI="#_b22715d12d722a8c2a803f9d08ead82b93af6a">
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                    <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>YIWSzq8z9rsvyPgA5QbU5yQqGxSp/Si0Xrb5vinCIC4=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>
        <ds:SignatureValue>NDwUkBXEjziI=</ds:SignatureValue>
<ds:KeyInfo>
            <ds:X509Data>
                <ds:X509Certificate>MIIESDC=</ds:X509Certificate>
            </ds:X509Data>
        </ds:KeyInfo>
    </ds:Signature>
    <samlp:Status>
        <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
    </samlp:Status>
    <saml:Assertion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" ID="_ca48e66ea95d993c44588984bfe334a87e8fc496f1" Version="2.0" IssueInstant="2019-01-16T10:03:29Z">
        <saml:Issuer>https://sso.domain.com/simplesaml/saml2/idp/metadata.php</saml:Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ds:SignedInfo>
                <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
    <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
  <ds:Reference URI="#_ca48e66ea95d993c44588984bfe334a87e8fc496f1">
                    <ds:Transforms>
                        <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                    <ds:DigestValue>lQbmjJZSm+s7ANl840IeQtOb0ei+D7cNWS3u0g08uXA=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>S0ywaXbKZA=</ds:SignatureValue>
<ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>MIIESDC=</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>
        <saml:Subject>
            <saml:NameID SPNameQualifier="https://cloud.domain.com/apps/user_saml/saml/metadata" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient">_41a70cf9ab6c6211faa33148135ee95e5a</saml:NameID>
            <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                <saml:SubjectConfirmationData NotOnOrAfter="2019-01-16T10:08:29Z" Recipient="https://cloud.domain.com/apps/user_saml/saml/acs" InResponseTo="ONELOGIN_e7968ec09c0f2aaaaaaaaaaaaaaaaaa"/>
            </saml:SubjectConfirmation>
        </saml:Subject>
        <saml:Conditions NotBefore="2019-01-16T10:02:59Z" NotOnOrAfter="2019-01-16T10:08:29Z">
            <saml:AudienceRestriction>
                <saml:Audience>https://cloud.domain.com/apps/user_saml/saml/metadata</saml:Audience>
            </saml:AudienceRestriction>
        </saml:Conditions>
        <saml:AuthnStatement AuthnInstant="2019-01-16T09:54:44Z" SessionNotOnOrAfter="2019-01-17T09:54:44Z" SessionIndex="_367ed11ac48c2ceffc520034facacb5c5718df0b70">
            <saml:AuthnContext>
                <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
            </saml:AuthnContext>
        </saml:AuthnStatement>
        <saml:AttributeStatement>
            <saml:Attribute Name="urn:oid:2.5.4.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">mlastname</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="urn:oid:2.5.4.4" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">lastname</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="urn:oid:2.16.840.1.113730.3.1.241" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">firstname lastname</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="urn:oid:2.5.4.42" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">firstname</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">firstname.lastname@company.com</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="urn:oid:0.9.2342.19200300.100.1.1" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">mlastname</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="memberOf" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">cn=nextcloud,ou=services,dc=company,dc=com</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="entryDN" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">cn=mlastname,ou=people,dc=company,dc=com</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="groups" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
                <saml:AttributeValue xsi:type="xs:string">nextcloud</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
    </saml:Assertion>
</samlp:Response>
```

**Comment by ChessSpider** [comment]
**I just tested with nextcloud 15.0.0 and that works !**

**Comment by danielkesselberg** [comment]
https://github.com/robrichards/xmlseclibs/blob/0f5466070e2a0f2d5d7f41968afdbbf982eea69c/src/XMLSecurityDSig.php#L501

Error is coming from this place. Could you edit this file and insert below `$includeCommentNodes = true;` in line 475: `var_dump($refNode, $refNode->getAttribute("URI"));`

**Comment by ChessSpider** [comment]
```
object(DOMElement)#1682 (18) { ["tagName"]=> string(12) "ds:Reference" ["schemaTypeInfo"]=> NULL ["nodeName"]=> string(12) "ds:Reference" ["nodeValue"]=> string(44) "jr4nFRQCbREbAbdot8UovRd/sPvliWSOAHYK6RNq20s=" ["nodeType"]=> int(1) ["parentNode"]=> string(22) "(object value omitted)" ["childNodes"]=> string(22) "(object value omitted)" ["firstChild"]=> string(22) "(object value omitted)" ["lastChild"]=> string(22) "(object value omitted)" ["previousSibling"]=> string(22) "(object value omitted)" ["nextSibling"]=> NULL ["attributes"]=> string(22) "(object value omitted)" ["ownerDocument"]=> string(22) "(object value omitted)" ["namespaceURI"]=> string(34) "http://www.w3.org/2000/09/xmldsig#" ["prefix"]=> string(2) "ds" ["localName"]=> string(9) "Reference" ["baseURI"]=> string(14) "/var/www/html/" ["textContent"]=> string(44) "jr4nFRQCbREbAbdot8UovRd/sPvliWSOAHYK6RNq20s=" } string(44) "#_246d96a936a75a936152ec332c46b0cb8962eb11dc"
```

Additionally, I get a  ```preg_replace(): Compilation failed: invalid range in character class at offset 8 at /var/www/html/apps/user_saml/3rdparty/vendor/robrichards/xmlseclibs/src/Utils/XPath.php#42``` immediately preceding the error stated above in my nextcloud.log. Sorry i just noticed that.

**Comment by danielkesselberg** [comment]
A few people reported troubles after update to 15.0.2 because they run nextcloud behind a reverse proxy without proper configuration: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse

Maybe this is related to your issue?

**Comment by mvitale1989** [comment]
I can confirm i was affected by the same problem, and setting the `overwriteprotocol` and `overwritehost` in config.php solved the issue for me. Thanks!

**Comment by ChessSpider** [comment]
issue fixed for me without changing anything, apperantly. Really weird.
If it returns ill try @mvitale1989 suggestion as i know its misconfigured right now
thanks everyone!
